### ISSUE TITLE
directory tree too deep

### ISSUE THREAD

**Issue by bbaassssiiee** [rothgar/ansible-tomcat#2]
These directories do the work, but they were in the wrong place when I tried to install the role in my roles subdir of my project. 
    files       handlers    tasks       templates   vars

In effect they were in this dir: MyProject/roles/rothgar.tomcat_and_java/roles/common

I would expect them to end up instead in: MyProject/roles/rothgar.tomcat_and_java

**Comment by rothgar** [comment]
Installed roles keep the same directory structure inside a roles directory.

eg

```
ansible-galaxy install rothgar.tomcat_and_java
```

by default wild be installed in /etc/ansible/roles/rothgar.tomcat_and_java with the roles subdirectory. You then can use the role inside a playbook with

```
- hosts: all
  roles:
    - role: rothgar.tomcat_and_java
      openjdk: True
```

Ansible runs will look in all configured roles paths for the necessary roles. If you want to specify a folder for install you can use `--roles-path=/path/to/install` instead.

Does that help?

**Comment by bbaassssiiee** [comment]
1. Don't assume your role is allowed in my /etc/ansible/roles. 
   I have a file 'requirements.yml':
   ---
   - src: rothgar.tomcat_and_java
     path: roles

To re-use your role local to my test project folder I do:
ansible-galaxy install --force -r requirements.yml
output
- downloading role 'tomcat_and_java', owned by rothgar
- downloading role from https://github.com/rothgar/ansible-tomcat/archive/master.tar.gz
- extracting rothgar.tomcat_and_java to roles/rothgar.tomcat_and_java
- rothgar.tomcat_and_java was installed successfully

Now this does not compute because the directory roles/rothgar.tomcat_and_java contains another roles directory with a 'common' role. If I move everything in that directory 2 levels up (mv \* ../..) then some stuff starts to work. (unfortunately with more errors.)

summary: non-relocatable role due to directory structure.

**Comment by rothgar** [comment]
@bbaassssiiee I think I fixed the directory structure so It will work as expected for you. Please let me know if this works now.
I think galaxy installs may take a bit longer to update from the upstream repo but it should be ready to test soon.

**Comment by bbaassssiiee** [comment]
Yes the directory structure is OK like this.
